name: build-web 

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST_PATH: '${{ github.event.repository.name }}/${{ github.sha }}/'
      PUBLIC_URL: 'https://web.onekey-asset.com/${{ github.event.repository.name }}/${{ github.sha }}/'
      NODE_ENV: 'production'
      CI: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@onekeyhq'
          node-version: '16.x'

      - name: Install Dependency
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn

      - name: Build Target
        env:
          PUBLIC_URL: ${{ env.PUBLIC_URL }}
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          yarn build
